// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awlhtgidvjkavnyzuspq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bGh0Z2lkdmprYXZueXp1c3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Njg0ODEsImV4cCI6MjA3MTA0NDQ4MX0.86f9rcenSiiz0n85g9rXv8y1IxPQRVzquD4TfznwFGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});